### ISSUE TITLE
Typo in example notebook

### ISSUE THREAD

**Issue by zilch42** [drob-xx/TopicTuner#16]
Hi there, cool package. I'm just starting to play around with it. 

Just wanted to let you know that there is a typo in the code in the Google colab example notebook.

`lastRunResultsDF = tmt.psuedoGridSearch([*range(62,71)], [x/100 for x in range(10,101,10)])`

pseudo is misspelled so that line doesn't run. It's also misspelled throughout the text. Simple find and replace should do it.

**Comment by zilch42** [comment]
Actually there a few things in the example notebook that could do with updating. It looks like the code may have been updated several times be the explanation text hasn't been rewritten to match. Some other examples as I'm reading through:

"In the next cell 20 random searches will be run using randomly chosen `min_cluster_size` values between 120 and 150..."
code: `range(30,151)`

"TMT.visualizeSearch produces a plotly parallel coordinates graph. You can pass it TMT.ResultsDF to get a view of all the searches, or pass it the results from a particular search."
next few cells don't run `TMT.visualizeSearch`

**Comment by drob-xx** [comment]
Yup. I don't run the notebook through the test harness yet. There were a bunch of minor changes (including fixing the psuedo/pseudo misspelling in a previous version. I'll get it fixed. Thanks!

**Comment by drob-xx** [comment]
Fixed.
