### ISSUE TITLE
How to use with wrap

### ISSUE THREAD

**Issue by cdolek** [drob-xx/TopicTuner#21]
I'm using `wrapBERTopicModel` and providing my own model. I see that wrapping returns the following.

```python
        return TopicModelTuner(
            embedding_model=BERTopicModel.embedding_model,
            reducer_model=BERTopicModel.umap_model,
            hdbscan_model=BERTopicModel.hdbscan_model,
        )
```

Following the provided notebook, next step is to create embeddings. But when I execute that I get the following error:

```python
----> 1 tmt.createEmbeddings(docs)

[/usr/local/lib/python3.10/dist-packages/topictuner/topictuner.py](https://localhost:8080/#) in createEmbeddings(self, docs)
    180         if np.all(docs != None):
    181             self.docs = docs
--> 182         self.embeddings = self.embedding_model.encode(self.docs)
    183 
    184     def reduce(self):

AttributeError: 'SentenceTransformerBackend' object has no attribute 'encode'
```

Help appreciated, thank you :)

**Comment by drob-xx** [comment]
What class is `BERTopicModel.embedding_model`? There are a couple of different ways to do this and if you show more of your setup code I might be able to suggest an alternative. Your embedding_model doesn't support `.encode` but there are other ways of using your own embedding.

**Comment by cdolek** [comment]
Thank you for the swift response! Here is a snippet:

```python
...
...
sentence_model = SentenceTransformer("all-MiniLM-L6-v2")
embeddings = sentence_model.encode(docs, show_progress_bar=True)


topic_model = BERTopic(
                        umap_model=umap_model, 
                        hdbscan_model=hdbscan_model,
                        ctfidf_model=ctfidf_model,
                        embedding_model=sentence_model

              )
              
topics, probs = topic_model.fit_transform(docs, embeddings)
```

**Comment by drob-xx** [comment]
I'm really not clear on what you are trying to do? Why are you generating the embeddings manually and then using them for the BERTopic model? `all-MiniLM-L6-v2` is the default sentence model - not sure why you are doing this manually? Also, why are you wrapping the BERTopic model? How about just generating using TopicTuner and then getting a BERTopic model?

**Comment by cdolek** [comment]
Sorry I'm new to this, let me do that now.

**Comment by drob-xx** [comment]
Yah the problem looks like it has something to do with how BERTopic handles the embedding model that you are passing in. However, that model is the same as would be created by default by BERTopic. It seems to work if you don't pass the model in. Also, it seems to me that in most, if not all, use cases you should be able to create the primary model in TopicTuner and avoid .wrap all together.
